### ISSUE TITLE
Toon thermostat broken?

### ISSUE THREAD

**Issue by pdwonline** [cyberjunky/home-assistant-toon_climate#39]
I use this component for some years and it worked fine. However since I installed HA version 2022.6 it doesn't work anymore
My log says:

````
2022-06-05 20:59:55 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities climate.toon_thermostaat or it is/they are currently not available

2022-06-05 21:00:45 ERROR (MainThread) [custom_components.toon_climate.climate] Cannot poll Toon thermostaat using url: http://192.168.0.200:80/happ_thermstat?action=getThermostatInfo

````

However; when I copy paste the URL in a browser, It does actually respond:

````
{"result":"ok", "currentTemp":"1977", "currentSetpoint":"1400", "currentInternalBoilerSetpoint":"6", "programState":"0", "activeState":"-1", "nextProgram":"-1", "nextState":"-1", "nextTime":"0","nextSetpoint":"0","randomConfigId":"1804289383","errorFound":"255","connection":"0","burnerInfo":"0","otCommError":"0","currentModulationLevel":"0"}
````

**Comment by compujunk** [comment]
here the same after installing HA version 2022.6

**Comment by cyberjunky** [comment]
@pdwonline @compujunk i just upgraded to 2022.6.2 and it still working, what versions are you on now?

**Comment by compujunk** [comment]
I have also upgraded to 2022.6.2 and its working again

________________________________
Van: Ron Klinkien ***@***.***>
Verzonden: maandag 6 juni 2022 16:25
Aan: cyberjunky/home-assistant-toon_climate ***@***.***>
CC: compujunk ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [cyberjunky/home-assistant-toon_climate] Toon thermostat broken? (Issue #39)


@pdwonline<https://github.com/pdwonline> @compujunk<https://github.com/compujunk> i just upgraded to 2022.6.2 and it is still working, what versions are you on now?

**Comment by pdwonline** [comment]
> @pdwonline @compujunk i just upgraded to 2022.6.2 and it is still working, what versions are you on now?

Updated to 2022.6.3 and still not working here. Should I do something after updating to get this woking again?

**Comment by cyberjunky** [comment]
@pdwonline did you get it to work? Still working here...

**Comment by ElStupid** [comment]
For me this issue also exists since upgrade to latest version of Toon Climate, couple of days ago.

`2022-07-29 11:06:12 ERROR (MainThread) [custom_components.toon_climate.climate] Timeout error occurred while polling Toon Thermostaat using url: http://192.168.30.28:80/happ_thermstat?action=getThermostatInfo`

**Comment by cyberjunky** [comment]
Are you sure the toon is online, and has same IP address?
Open the url in a webbrowser to check.

**Comment by ElStupid** [comment]
> Are you sure the toon is online, and has same IP address? Open the url in a webbrowser to check.

Good one, didn't try, because Toon is working and I confirmed it's IP address is still correct. 
In the browser the URL wasn't functioning either. I did restart Toon from the interface which caused it to hang so I had to take it off the wall. Issue resolved now, sorry for bothering and thanks for me pointing me out!
